### ISSUE TITLE
Is there any chance for FOR Delta Encoding？

### ISSUE THREAD

**Issue by likun666661** [spiraldb/fastlanes-rs#13]
I see the FastLanes can use For encoding。And I wonder the delta encoding in fastlanes is for encoding?

**Comment by gatesn** [comment]
Yes, we plan to add FOR, and maybe also RLE and Dict.

The game then is deciding which kernels we wish to fuse together. But I'm not exactly sure what you mean by your question?

**Comment by gatesn** [comment]
I've now added FoR and Delta. Though not FoR+Delta. Please re-open if I've misunderstood
